### ISSUE TITLE
SDK登录失败，cloudbase论坛没人回复，您是否遇到相同问题？

### ISSUE THREAD

**Issue by dingronghui** [0Kirby/CloudbaseFlutterDemo#1]
_cloudFunction() async {
    CloudBaseCore core =CloudBaseCore.init({
      // 填写您的云开发 env
      'env': '我的envid',
      // 填写您的移动应用安全来源凭证
      // 生成凭证的应用标识必须是 Android 包名或者 iOS BundleID
      'appAccess': {
        // 凭证
        'key': '我的appkey',
        // 版本
        'version': '1'
      },
      'region': 'ap-guangzhou',//Google查到前端遇到相同问题，需要加的参数
      // 请求超时时间（选填）
      'timeout': 3000
    });
// 获取登录状态
    CloudBaseAuth auth = CloudBaseAuth(core);
    CloudBaseAuthState authState = await auth.getAuthState();
// 唤起匿名登录
    if (authState == null) {
      await auth.signInAnonymously().then((success) {
        // 登录成功
        print(success);
      }).catchError((err) {
        // 登录失败
        print(err);
      });
    }
    CloudBaseFunction cloudbase = CloudBaseFunction(core);
    Map<String, dynamic> data = {'code': _code, 'stdin': _stdin};
    CloudBaseResponse res = await cloudbase.callFunction(_function, data);
    setState(() {
      _output = res.data;
    });
  }
匿名登录报问题:
flutter: CloudBaseError [INVALID_REGION]: Environment create in ap-guangzhou cannot access in ap-shanghai
应该是SDK请求参数的问题
我目前使用的是免费版套餐，只有广州一个环境

**Comment by 0Kirby** [comment]
你再检查一下env和region，实在不行用上海区创建的环境操作

**Comment by dingronghui** [comment]
> 你再检查一下env和region，实在不行用上海区创建的环境操作

谢谢答复，找了很多地方，最终在文档里面找到一处备注，Flutter只能使用上海环境
